### ISSUE TITLE
About version of torch point 3d and omegaconf

### ISSUE THREAD

**Issue by cathylacus** [pvnieo/GeomFmaps_pytorch#4]
Thank for your work！
I install  torch point 3d a==1.3.0 and omegaconf==1.4 on a platform of cuda10.2
But when I training，it have a error：

Traceback (most recent call last):
  File "train.py", line 56, in <module>
    train(params)
  File "train.py", line 26, in train
    trainset = ShapeMatchingDatasetWrapper(params, train=True)
  File "/test/liwei/FMNET/GeomFmaps_pytorch-master/geomfmaps/shape_matching_dataset.py", line 235, in __init__
    params = OmegaConf.create(hparams)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 53, in create
    raise RuntimeError("Unsupported type {}".format(type(obj).__name__))
RuntimeError: Unsupported type DictConfig

When I change omegaconf to 2.1.1，I can load yaml file，but It have another error：

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hydra-core 0.11.3 requires omegaconf<1.5,>=1.4, but you have omegaconf 2.1.1 which is incompatible.

when training，it says：

Traceback (most recent call last):
  File "train.py", line 56, in <module>
    train(params)
  File "train.py", line 22, in train
    model = GeomFmapNet(params.n_feat, params.in_grid_size, params.lambda_).to(device)
  File "/test/liwei/FMNET/GeomFmaps_pytorch-master/geomfmaps/model.py", line 131, in __init__
    self.feature_extractor = KPConvFeatureExtractor(n_feat=n_feat, in_grid_size=in_grid_size)
  File "/test/liwei/FMNET/GeomFmaps_pytorch-master/geomfmaps/model.py", line 108, in __init__
    in_grid_size=in_grid_size
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/torch_points3d/applications/kpconv.py", line 48, in KPConv
    return factory.build()
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/torch_points3d/applications/modelfactory.py", line 73, in build
    return self._build_unet()
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/torch_points3d/applications/kpconv.py", line 60, in _build_unet
    return KPConvUnet(model_config, None, None, modules_lib, **self.kwargs)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/torch_points3d/applications/kpconv.py", line 77, in __init__
    super(BaseKPConv, self).__init__(model_config, model_type, dataset, modules)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/torch_points3d/models/base_architectures/unet.py", line 363, in __init__
    self._init_from_compact_format(opt, model_type, dataset, modules_lib)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/torch_points3d/models/base_architectures/unet.py", line 410, in _init_from_compact_format
    self.save_sampling_id = opt.down_conv.save_sampling_id
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 354, in __getattr__
    key=key, value=None, cause=e, type_override=ConfigAttributeError
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/base.py", line 196, in _format_and_raise
    type_override=type_override,
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/root/anaconda3/envs/geo_torch/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key save_sampling_id
    full_key: down_conv.save_sampling_id
    object_type=dict
I think the problem is the unmatching between torch point 3d and omegaconf!
So I want kown which version of these package on your environment.Thanks！

**Comment by pvnieo** [comment]
This is an error related to torch-points3d version, I don't remember which version I used, and this code Is no longer maintained, I suggest using the code of [diffusion net](https://github.com/nmwsharp/diffusion-net/tree/master/experiments/functional_correspondence), which is more recent, provides better results, and is easy to use!
